USE [master]
GO
/****** Object:  Database [NEGBAS]    Script Date: 14-07-2024 14:39:17 ******/
CREATE DATABASE [NEGBAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NEGBAS_Data', FILENAME = N'/var/opt/mssql/data/NEGBAS_Data.mdf' , SIZE = 27392000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 512000KB )
 LOG ON 
( NAME = N'NEGBAS_Log', FILENAME = N'/var/opt/mssql/data/NEGBAS_log.ldf' , SIZE = 181184KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [NEGBAS] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NEGBAS].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [NEGBAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NEGBAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NEGBAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NEGBAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NEGBAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [NEGBAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NEGBAS] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [NEGBAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NEGBAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NEGBAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NEGBAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NEGBAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NEGBAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NEGBAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NEGBAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NEGBAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NEGBAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NEGBAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NEGBAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NEGBAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NEGBAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NEGBAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NEGBAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NEGBAS] SET RECOVERY FULL 
GO
ALTER DATABASE [NEGBAS] SET  MULTI_USER 
GO
ALTER DATABASE [NEGBAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NEGBAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NEGBAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NEGBAS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'NEGBAS', N'ON'
GO